### ISSUE TITLE
Add new building blocks

### ISSUE THREAD

**Issue by lipelopesoliveira** [lipelopesoliveira/pyCOFBuilder#32]
### Motivação 

![image](https://user-images.githubusercontent.com/33868364/186947009-b0ac12a5-173b-4e9b-89a1-ae873f03ed6b.png)

![image](https://user-images.githubusercontent.com/33868364/186976947-406e1b02-6436-449d-aa2e-23fa13ab434e.png)

![image](https://user-images.githubusercontent.com/33868364/186977265-3bb15231-8720-43c9-88fa-2d6a97ed527f.png)

![image](https://user-images.githubusercontent.com/33868364/188971177-bb6f3ca8-928c-4f5e-926f-67be659032dc.png)

**Comment by jerichooconnell** [comment]
Hello, very cool package!

If I wanted to add a new building block what sort of information would I need? I see the json files but I'm not sure how to input the structural information. Do you think the package would work if I wanted to try out building blocks that have never been used for COFs before?

Thanks!

**Comment by lipelopesoliveira** [comment]
Hi @jerichooconnell,

I'm glad you liked pyCOFBuilder.

> If I wanted to add a new building block what sort of information would I need? I see the json files but I'm not sure how to input the structural information. 

To add a new custom building block you only need the atomic positions of the molecule. You can take a look at [this](https://github.com/lipelopesoliveira/pyCOFBuilder/blob/master/examples/BuildingBlock_creation/create_building_block.ipynb) example for more details. 

> Do you think the package would work if I wanted to try out building blocks that have never been used for COFs before?

Yes. As long as the new building blocks follows the geometric pattern supported by the current implementation on the package, _i.e._, the molecule has a geometry that is linear, triangular, squared or hexagonal, it should work. 

But if you have any problems or want some help please let me know, I'll be happy to help!

**Comment by jerichooconnell** [comment]
Thanks so much! I'll take a look at the example.

**Comment by tianwangababab** [comment]
Hi, I read the article you published and am very interested in this code package.
However, I'm having problems creating a new build block. I have questions about what the molecules imported via .csjon format look like. I tried to import both Figure A and B building blocks, but both failed. the B building block code does not work at all.
It should be that my understanding of the explicit build rules you describe is off. Can you explain the rules in more detail or provide some examples. Or can you provide the package I want for this T4 structured building block（TAM monomer for COf300）.
Thank you very much！！！
![微信图片_20240429123207](https://github.com/lipelopesoliveira/pyCOFBuilder/assets/168347252/8a38dce5-7e2e-4ad8-85a9-c2a8fa8f0d15)

**Comment by lipelopesoliveira** [comment]
Hi @tianwangababab

Thank you for demonstrating interest in using pyCOFBuilder. I'm sorry to hear that you could not create the building blocks that you are interest. 

This building block is already available on pyCOFBuilder, the name is `D4_TTPM`. So, to create the COF-300 structure you can use the name: `D4_TTPM_NH2_H-L2_BENZ_CHO_H-DIA_A-1`.

I've just realize that it is not on the online documentation. Sorry for that, I'll fix it. 

Regarding the creation of the building block, can you provide me more details on the errors you faced. I understand that right now the instructions may be a little to shallow, I'm working to improve the details (I'm considering recording a tutorial on video). In case you have some suggestions on how to improve it please let me know. 

In case you face any other problems please let me know.

**Comment by tianwangababab** [comment]
OK, thanks so much!!! If I have a problem, I'll talk to you. The implementation of this code package will help me a lot in my research and should also have a great impact on the development of COFs.
