### ISSUE TITLE
How to build a new cof module monomer

### ISSUE THREAD

**Issue by Qwsetygfhuhhf** [lipelopesoliveira/pyCOFBuilder#44]
Hello, I would like to ask how to build a new cof module monomer. For example, I built a gjf file of a new cof monomer through gview, but I noticed that a json file is also needed for pyCOFBulider to identify it. May I ask how this Json file is generated through gjf file?

**Comment by lipelopesoliveira** [comment]
I will launch in a few days a uptated version of pyCOFBuilder that will allow the conversion from a `gjf` or `xyz` file to the `json` format.

**Comment by Qwsetygfhuhhf** [comment]
Well, thanks
when I tried to create a S4+T3-3D cof, I used the two topological structures provided by you in the framework, namely DIA and BOR. However, after attempting to modify **the [net] value in lines 209 and 210 of the code 'self.available_stacking[net]'** in the framework, I found that each stacking structure failed to successfully create the 3DCOF. I would like to ask if you also encountered this problem when creating the 3DCOF? Looking forward to your reply, thank you.

**Comment by Qwsetygfhuhhf** [comment]
Well, thank you so much 
when I tried to create a S4+T3-3D cof, I used the two topological structures provided by you in the framework, namely DIA and BOR. However, after attempting to modify the **[net] value in lines 209 and 210 of the code 'self.available_stacking[net]'** in the framework, I found that each stacking structure failed to successfully create the 3DCOF. I would like to ask if you also encountered this problem when creating the 3DCOF? Looking forward to your reply, thank you.

**Comment by lipelopesoliveira** [comment]
Dear @Qwsetygfhuhhf,

I've updated the code to add a new [jupyter notebook](https://github.com/lipelopesoliveira/pyCOFBuilder/blob/master/examples/BuildingBlock_creation/create_building_block.ipynb) to help in the creation of custom building blocks. Please take a look
