### ISSUE TITLE
Addition of building block into core library

### ISSUE THREAD

**Issue by BurnerJ** [lipelopesoliveira/pyCOFBuilder#63]
Could we please add this ditopic building block to the core library (added with .txt extension because of GitHub file type support)? It comes from this paper -- DOI: 10.1002/cssc.201903545

Thanks!
[ECBZ.txt](https://github.com/user-attachments/files/15889421/ECBZ.txt)

**Comment by lipelopesoliveira** [comment]
Closed by #64
